import { clsx } from "clsx";

const IOC_TO_FLAG_ICONS_CODE: Record<string, string> = {
  AFG: "af",
  AIA: "ai",
  ALB: "al",
  ALG: "dz",
  AND: "ad",
  ANG: "ao",
  ANT: "cw",
  ARG: "ar",
  ARM: "am",
  ARU: "aw",
  ASA: "as",
  AUS: "au",
  AUT: "at",
  AZE: "az",
  BAH: "bs",
  BAN: "bd",
  BAR: "bb",
  BDI: "bi",
  BEL: "be",
  BEN: "bj",
  BER: "bm",
  BES: "bq",
  BHU: "bt",
  BIH: "ba",
  BIZ: "bz",
  BLR: "by",
  BOL: "bo",
  BOT: "bw",
  BRA: "br",
  BRN: "bn",
  BRU: "bn",
  BUL: "bg",
  BUR: "bf",
  CAF: "cf",
  CAM: "kh",
  CAN: "ca",
  CAY: "ky",
  CGO: "cg",
  CHA: "td",
  CHI: "cl",
  CHN: "cn",
  CIV: "ci",
  CMR: "cm",
  COD: "cd",
  COK: "ck",
  COL: "co",
  COM: "km",
  CPV: "cv",
  CRC: "cr",
  CRO: "hr",
  CUB: "cu",
  CUW: "cw",
  CYP: "cy",
  CZE: "cz",
  DEN: "dk",
  DJI: "dj",
  DMA: "dm",
  DOM: "do",
  ECU: "ec",
  EGY: "eg",
  ENG: "gb-eng",
  ERI: "er",
  ESA: "sv",
  ESP: "es",
  EST: "ee",
  ETH: "et",
  FIJ: "fj",
  FIN: "fi",
  FLK: "fk",
  FRA: "fr",
  FRO: "fo",
  FSM: "fm",
  GAB: "ga",
  GAM: "gm",
  GBS: "gw",
  GBR: "gb",
  GEO: "ge",
  GEQ: "gq",
  GER: "de",
  GGY: "gg",
  GHA: "gh",
  GIB: "gi",
  GRE: "gr",
  GRL: "gl",
  GRN: "gd",
  GUA: "gt",
  GUI: "gn",
  GUM: "gu",
  GUY: "gy",
  HAI: "ht",
  HKG: "hk",
  HON: "hn",
  HUN: "hu",
  IMN: "im",
  INA: "id",
  IND: "in",
  IRI: "ir",
  IRL: "ie",
  IRQ: "iq",
  ISL: "is",
  ISR: "il",
  ISV: "vi",
  ITA: "it",
  IVB: "vg",
  JAM: "jm",
  JEY: "je",
  JOR: "jo",
  JPN: "jp",
  KAZ: "kz",
  KEN: "ke",
  KGZ: "kg",
  KIR: "ki",
  KOR: "kr",
  KOS: "xk",
  KSA: "sa",
  KUW: "kw",
  LAO: "la",
  LAT: "lv",
  LBA: "ly",
  LBN: "lb",
  LBR: "lr",
  LCA: "lc",
  LES: "ls",
  LIE: "li",
  LTU: "lt",
  LUX: "lu",
  MAC: "mo",
  MAD: "mg",
  MAF: "mf",
  MAR: "ma",
  MAS: "my",
  MAW: "mw",
  MDA: "md",
  MDV: "mv",
  MEX: "mx",
  MGL: "mn",
  MHL: "mh",
  MKD: "mk",
  MLI: "ml",
  MLT: "mt",
  MNE: "me",
  MNP: "mp",
  MON: "mc",
  MOZ: "mz",
  MRI: "mu",
  MTN: "mr",
  MYA: "mm",
  NAM: "na",
  NCA: "ni",
  NCL: "nc",
  NED: "nl",
  NEP: "np",
  NFK: "nf",
  NGR: "ng",
  NIG: "ne",
  NIU: "nu",
  NOR: "no",
  NRU: "nr",
  NZL: "nz",
  OMA: "om",
  PAK: "pk",
  PAN: "pa",
  PAR: "py",
  PER: "pe",
  PHI: "ph",
  PLE: "ps",
  PLW: "pw",
  PNG: "pg",
  POL: "pl",
  POR: "pt",
  PRK: "kp",
  PUR: "pr",
  PYF: "pf",
  QAT: "qa",
  ROU: "ro",
  RSA: "za",
  RUS: "ru",
  RWA: "rw",
  SAM: "ws",
  SCO: "gb-sct",
  SEN: "sn",
  SEY: "sc",
  SGP: "sg",
  SKN: "kn",
  SLE: "sl",
  SLO: "si",
  SMR: "sm",
  SOL: "sb",
  SOM: "so",
  SRB: "rs",
  SRI: "lk",
  SSD: "ss",
  STP: "st",
  SUD: "sd",
  SUI: "ch",
  SUR: "sr",
  SVK: "sk",
  SWE: "se",
  SWZ: "sz",
  SYR: "sy",
  TAN: "tz",
  TGA: "to",
  THA: "th",
  TJK: "tj",
  TKL: "tk",
  TKM: "tm",
  TLS: "tl",
  TOG: "tg",
  TPE: "tw",
  TTO: "tt",
  TUN: "tn",
  TUR: "tr",
  TUV: "tv",
  UAE: "ae",
  UGA: "ug",
  UKR: "ua",
  URU: "uy",
  USA: "us",
  UZB: "uz",
  VAN: "vu",
  VEN: "ve",
  VIE: "vn",
  VIN: "vc",
  WAL: "gb-wls",
  WLF: "wf",
  YEM: "ye",
  ZAM: "zm",
  ZIM: "zw",
};

export function getFlagIconCode(code: string | null | undefined) {
  if (!code) return null;

  const normalized = code.trim().toUpperCase();
  if (!normalized) return null;

  if (normalized.length === 2) {
    return normalized.toLowerCase();
  }

  return IOC_TO_FLAG_ICONS_CODE[normalized] ?? null;
}

type FlagProps = {
  code: string | null | undefined;
  className?: string;
  title?: string;
};

export function Flag({ code, className, title }: FlagProps) {
  const flagCode = getFlagIconCode(code);

  if (!flagCode) {
    return (
      <span
        className={clsx("inline-block h-[0.75em] w-[1.125em] rounded-[2px] bg-slate-200 align-[-0.1em]", className)}
        aria-hidden="true"
      />
    );
  }

  return (
    <span
      className={clsx("fi", `fi-${flagCode}`, "inline-block h-[0.75em] w-[1.125em] rounded-[2px] align-[-0.1em]", className)}
      aria-hidden="true"
      title={title}
    />
  );
}
