#!/usr/bin/env python3
"""Apply manually completed ranking/profile review data."""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from lib.capture import save_json

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger("ittf_review_apply")

DEFAULT_DICT_PATH = Path("scripts/data/translation_dict_v2.json")


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _dict_key(original: str) -> str:
    return " ".join((original or "").strip().split()).lower()


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _apply_translations(review: dict[str, Any], dict_path: Path) -> int:
    dictionary = _load_json(dict_path) if dict_path.exists() else {"metadata": {}, "entries": {}}
    dictionary.setdefault("metadata", {})
    entries = dictionary.setdefault("entries", {})
    added = 0
    for item in review.get("missing_translations", []):
        if not isinstance(item, dict):
            continue
        original = str(item.get("original") or "").strip()
        translated = str(item.get("translated") or "").strip()
        if not original or not translated:
            continue
        key = _dict_key(original)
        categories = item.get("categories") or ["others"]
        if not isinstance(categories, list):
            categories = ["others"]
        previous = entries.get(key)
        entries[key] = {
            "original": original,
            "translated": translated,
            "categories": categories,
            "source": "manual_review",
            "review_status": "reviewed",
            "updated_at": _utc_now_iso(),
        }
        if previous != entries[key]:
            added += 1
    save_json(dict_path, dictionary)
    return added


def _row_matches(row: dict[str, Any], weekly: dict[str, Any]) -> bool:
    fields = ["rank", "name", "country_code", "points"]
    for field in fields:
        expected = weekly.get(field)
        if expected is None:
            continue
        if str(row.get(field) or "") != str(expected):
            return False
    return True


def _apply_ranking_ids(review: dict[str, Any], ranking_file: Path | None) -> int:
    if ranking_file is None:
        return 0
    ranking = _load_json(ranking_file)
    rows = ranking.get("rankings", [])
    if not isinstance(rows, list):
        raise ValueError(f"ranking file has invalid rankings list: {ranking_file}")

    applied = 0
    for item in review.get("unresolved_player_ids", []):
        if not isinstance(item, dict):
            continue
        resolution = item.get("resolution") or {}
        player_id = str(resolution.get("player_id") or "").strip()
        if not player_id:
            continue
        weekly = item.get("weekly") or {}
        profile_url = str(resolution.get("profile_url") or "").strip() or None
        for row in rows:
            if not isinstance(row, dict) or not _row_matches(row, weekly):
                continue
            row["player_id"] = player_id
            if profile_url:
                row["profile_url"] = profile_url
            row["id_resolution_status"] = "manual"
            applied += 1
            break

    save_json(ranking_file, ranking)
    return applied


def apply_review(
    review_path: Path,
    *,
    dict_path: Path = DEFAULT_DICT_PATH,
    ranking_file: Path | None = None,
) -> dict[str, int]:
    review = _load_json(review_path)
    return {
        "translations_added": _apply_translations(review, dict_path),
        "ranking_ids_applied": _apply_ranking_ids(review, ranking_file),
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Apply completed manual review JSON")
    parser.add_argument("--review", required=True, help="Review JSON generated by review_ranking_profile_outputs.py")
    parser.add_argument("--dict-path", default=str(DEFAULT_DICT_PATH))
    parser.add_argument("--ranking-file", default=None, help="Merged ranking JSON to patch with manual player IDs")
    return parser


def run(args: argparse.Namespace) -> int:
    summary = apply_review(
        Path(args.review),
        dict_path=Path(args.dict_path),
        ranking_file=Path(args.ranking_file) if args.ranking_file else None,
    )
    logger.info("Applied translations: %d", summary["translations_added"])
    logger.info("Applied ranking ids: %d", summary["ranking_ids_applied"])
    return 0


def main() -> None:
    parser = build_parser()
    sys.exit(run(parser.parse_args()))


if __name__ == "__main__":
    main()
